title: Not Yet a Paper
description: Thoughts & ideas on machine learning and physics. Mainly me trying to understanding things by explaining them.
author: "Markus Frank"

theme: minima

#base_url: /

# Minima social links
#twitter_username: -
github_username: friedchips
#linkedin_username: -
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/frontpage.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
